daemon off; pid /dev/null; worker_processes auto; error_log /dev/stderr info; events {
        worker_connections 1024;
}

http {
    etag off;
    server {
        listen 0.0.0.0:80;
        server_name upgs.dvdnow.arcade.cab s250video.dvdnow.arcade.cab *.dvdnow.arcade.cab dvdnow.arcade.cab;
        proxy_set_header x-galaxy-real-ip $remote_addr;
        location /api {
            proxy_pass http://dvdnow:8080;
            proxy_set_header X-Forwarded-For $remote_addr;
            proxy_set_header Host            $host;
        }
        location /upg {
            proxy_pass http://dvdnow:8080;
            proxy_set_header X-Forwarded-For $remote_addr;
            proxy_set_header Host            $host;
        }
	location / {
            proxy_pass http://dvdnow:8080;
            proxy_set_header X-Forwarded-For $remote_addr;
            proxy_set_header Host            $host;
	}
    }


}
